import type { BrowserName, BrowserCompatibilityFinding } from './types';

export interface BrowserFeatureDefinition {
  id: string;
  feature: string;
  kind: BrowserCompatibilityFinding['kind'];
  pattern: RegExp;
  minimums: Partial<Record<BrowserName, number>>;
  partialMinimums?: Partial<Record<BrowserName, number>>;
  unsupported?: BrowserName[];
  recommendation: string;
}

/** Versioned, deterministic web-platform knowledge. Versions are minimum stable releases. */
export const BROWSER_KNOWLEDGE_VERSION = '4.0.0';
export const BROWSER_FEATURES: readonly BrowserFeatureDefinition[] = [
  { id: 'webgpu', feature: 'WebGPU', kind: 'web-api', pattern: /navigator\.gpu\b/, minimums: { Chrome: 113, Edge: 113, Firefox: 141, Safari: 26 }, recommendation: 'Feature-detect navigator.gpu and provide a fallback.' },
  { id: 'view-transitions', feature: 'View Transitions API', kind: 'web-api', pattern: /document\.startViewTransition\b/, minimums: { Chrome: 111, Edge: 111, Firefox: 144, Safari: 18 }, recommendation: 'Feature-detect startViewTransition and provide a normal transition fallback.' },
  { id: 'popover', feature: 'Popover API', kind: 'web-api', pattern: /\.(?:showPopover|hidePopover|togglePopover)\s*\(|\b(?:popoverTargetElement|popoverTargetAction)\b|\bpopover\s*=\s*["'](?:auto|manual)["']/i, minimums: { Chrome: 114, Edge: 114, Firefox: 125, Safari: 17 }, recommendation: 'Feature-detect the Popover API or provide a dialog/menu fallback.' },
  { id: 'css-has', feature: 'CSS :has()', kind: 'css', pattern: /:has\s*\(/, minimums: { Chrome: 105, Edge: 105, Firefox: 121, Safari: 15.4 }, recommendation: 'Provide a fallback selector for browsers below the :has() baseline.' },
  { id: 'container-queries', feature: 'CSS container queries', kind: 'css', pattern: /@container\b/, minimums: { Chrome: 105, Edge: 105, Firefox: 110, Safari: 16 }, recommendation: 'Provide a media-query or layout fallback when container queries are unavailable.' },
  { id: 'css-nesting', feature: 'CSS nesting', kind: 'css', pattern: /(?:^|\})\s*[.#[:][^{]+\{[^{}]*&(?:\s|[.#[:])/m, minimums: { Chrome: 120, Edge: 120, Firefox: 117, Safari: 17.2 }, partialMinimums: { Chrome: 112, Edge: 112, Safari: 16.5 }, recommendation: 'Compile nested CSS or provide unnested rules for older targets.' },
  { id: 'css-subgrid', feature: 'CSS subgrid', kind: 'css', pattern: /grid-template-(?:rows|columns)\s*:\s*subgrid\b/i, minimums: { Chrome: 117, Edge: 117, Firefox: 71, Safari: 16 }, recommendation: 'Provide a regular grid fallback for browsers without subgrid.' },
  { id: 'color-mix', feature: 'CSS color-mix()', kind: 'css', pattern: /\bcolor-mix\s*\(/i, minimums: { Chrome: 111, Edge: 111, Firefox: 113, Safari: 16.2 }, recommendation: 'Provide a precomputed color fallback before color-mix().' },
  { id: 'backdrop-filter', feature: 'CSS backdrop-filter', kind: 'css', pattern: /(?:^|[;{\s])(?:-webkit-)?backdrop-filter\s*:/, minimums: { Chrome: 76, Edge: 79, Firefox: 103, Safari: 9 }, recommendation: 'Provide a background fallback for browsers without backdrop-filter.' },
  { id: 'focus-visible', feature: 'CSS :focus-visible', kind: 'css', pattern: /:focus-visible\b/, minimums: { Chrome: 86, Edge: 86, Firefox: 85, Safari: 15.4 }, recommendation: 'Keep a safe :focus fallback for keyboard focus styling.' },
  { id: 'structured-clone', feature: 'structuredClone()', kind: 'web-api', pattern: /\bstructuredClone\s*\(/, minimums: { Chrome: 98, Edge: 98, Firefox: 94, Safari: 15.4 }, recommendation: 'Use a compatible clone fallback for older browsers.' },
  { id: 'resize-observer', feature: 'ResizeObserver', kind: 'web-api', pattern: /\bnew\s+ResizeObserver\s*\(|\bResizeObserver\s*\(/, minimums: { Chrome: 64, Edge: 79, Firefox: 69, Safari: 13.1 }, recommendation: 'Load a ResizeObserver polyfill when older browsers are supported.' },
  { id: 'intersection-observer', feature: 'IntersectionObserver', kind: 'web-api', pattern: /\bnew\s+IntersectionObserver\s*\(|\bIntersectionObserver\s*\(/, minimums: { Chrome: 51, Edge: 15, Firefox: 55, Safari: 12.1 }, recommendation: 'Load a polyfill or provide an eager-loading fallback for older browsers.' },
  { id: 'abort-controller', feature: 'AbortController', kind: 'web-api', pattern: /\bnew\s+AbortController\s*\(/, minimums: { Chrome: 66, Edge: 16, Firefox: 57, Safari: 12.1 }, recommendation: 'Use a cancellation fallback or polyfill for older targets.' },
  { id: 'clipboard', feature: 'Async Clipboard API', kind: 'web-api', pattern: /navigator\.clipboard\b/, minimums: { Chrome: 66, Edge: 79, Firefox: 63, Safari: 13.1 }, recommendation: 'Feature-detect clipboard access and provide a manual copy fallback.' },
  { id: 'broadcast-channel', feature: 'BroadcastChannel', kind: 'web-api', pattern: /\bnew\s+BroadcastChannel\s*\(/, minimums: { Chrome: 54, Edge: 79, Firefox: 38, Safari: 15.4 }, recommendation: 'Use a storage-event or server-mediated fallback for older browsers.' },
  { id: 'dialog', feature: 'HTML dialog element', kind: 'web-api', pattern: /\.(?:showModal|close)\s*\(|<dialog\b/i, minimums: { Chrome: 37, Edge: 79, Firefox: 98, Safari: 15.4 }, recommendation: 'Provide dialog semantics and focus management through a compatible fallback.' },
  { id: 'web-bluetooth', feature: 'Web Bluetooth', kind: 'web-api', pattern: /navigator\.bluetooth\b/, minimums: { Chrome: 56, Edge: 79 }, unsupported: ['Firefox', 'Safari'], recommendation: 'Treat Web Bluetooth as an enhancement and provide a non-Bluetooth path.' },
  { id: 'file-system-access', feature: 'File System Access API', kind: 'web-api', pattern: /\b(?:showOpenFilePicker|showSaveFilePicker|showDirectoryPicker)\s*\(/, minimums: { Chrome: 86, Edge: 86 }, unsupported: ['Firefox', 'Safari'], recommendation: 'Provide input/download fallbacks when native file-system access is unavailable.' },
  { id: 'import-maps', feature: 'Import maps', kind: 'javascript', pattern: /<script[^>]+type=["']importmap["']/i, minimums: { Chrome: 89, Edge: 89, Firefox: 108, Safari: 16.4 }, recommendation: 'Bundle imports or provide an import-map fallback for older browsers.' },
  { id: 'optional-chaining', feature: 'Optional chaining', kind: 'javascript', pattern: /\?\./, minimums: { Chrome: 80, Edge: 80, Firefox: 74, Safari: 13.1 }, recommendation: 'Transpile optional chaining for older browser targets.' },
  { id: 'nullish-coalescing', feature: 'Nullish coalescing', kind: 'javascript', pattern: /\?\?=?/, minimums: { Chrome: 80, Edge: 80, Firefox: 72, Safari: 13.1 }, recommendation: 'Transpile nullish coalescing for older browser targets.' },
  { id: 'promise-all-settled', feature: 'Promise.allSettled()', kind: 'javascript', pattern: /\bPromise\.allSettled\s*\(/, minimums: { Chrome: 76, Edge: 79, Firefox: 71, Safari: 13 }, recommendation: 'Polyfill Promise.allSettled or use an equivalent aggregation strategy.' },
  { id: 'bigint', feature: 'BigInt', kind: 'javascript', pattern: /\bBigInt\s*\(|\b\d+n\b/, minimums: { Chrome: 67, Edge: 79, Firefox: 68, Safari: 14 }, recommendation: 'Avoid BigInt on older targets or provide a compatible numeric library.' },
  { id: 'array-at', feature: 'Array.prototype.at()', kind: 'javascript', pattern: /\.at\s*\(\s*-?\d+\s*\)/, minimums: { Chrome: 92, Edge: 92, Firefox: 90, Safari: 15.4 }, recommendation: 'Transpile or replace .at() when supporting older browsers.' },
  ...(
    [
      ['fetch','Fetch API','web-api',/\bfetch\s*\(/,42,39,14.1],['websocket','WebSocket','web-api',/\bnew\s+WebSocket\s*\(/,16,11,7],['service-worker','Service Worker','web-api',/navigator\.serviceWorker\b/,45,44,11.1],['web-worker','Web Worker','web-api',/\bnew\s+(?:Shared)?Worker\s*\(/,4,3.5,4],
      ['indexeddb','IndexedDB','web-api',/\bindexedDB\b/,24,16,10],['notifications','Notifications API','web-api',/\bNotification\.(?:requestPermission|permission)\b/,22,22,7],['geolocation','Geolocation API','web-api',/navigator\.geolocation\b/,5,3.5,5],['media-devices','MediaDevices','web-api',/navigator\.mediaDevices\b/,47,36,11],
      ['web-share','Web Share API','web-api',/navigator\.share\s*\(/,89,71,12.1],['payment-request','Payment Request API','web-api',/\bnew\s+PaymentRequest\s*\(/,61,55,11.1],['credentials','Credential Management API','web-api',/navigator\.credentials\b/,51,60,13],['permissions','Permissions API','web-api',/navigator\.permissions\b/,43,46,16],
      ['performance-observer','PerformanceObserver','web-api',/\bnew\s+PerformanceObserver\s*\(/,52,57,11],['mutation-observer','MutationObserver','web-api',/\bnew\s+MutationObserver\s*\(/,26,14,6.1],['request-idle-callback','requestIdleCallback','web-api',/\brequestIdleCallback\s*\(/,47,55,18.1],['offscreen-canvas','OffscreenCanvas','web-api',/\bnew\s+OffscreenCanvas\s*\(/,69,105,16.4],
      ['webgl2','WebGL 2','web-api',/getContext\s*\(\s*["']webgl2["']/,56,51,15],['webrtc','WebRTC','web-api',/\bnew\s+RTCPeerConnection\s*\(/,23,22,11],['screen-orientation','Screen Orientation API','web-api',/screen\.orientation\b/,38,43,16.4],['fullscreen','Fullscreen API','web-api',/\.requestFullscreen\s*\(/,71,64,16.4],
      ['picture-in-picture','Picture-in-Picture API','web-api',/requestPictureInPicture\s*\(/,70,100,13.1],['wake-lock','Screen Wake Lock API','web-api',/navigator\.wakeLock\b/,84,126,16.4],['speech-recognition','Speech Recognition','web-api',/\b(?:webkit)?SpeechRecognition\b/,25,999,14.1],['speech-synthesis','Speech Synthesis','web-api',/speechSynthesis\b/,33,49,7],
      ['url-pattern','URLPattern','web-api',/\bnew\s+URLPattern\s*\(/,95,999,999],['compression-stream','CompressionStream','web-api',/\bnew\s+(?:De)?CompressionStream\s*\(/,80,113,16.4],['transform-stream','TransformStream','web-api',/\bnew\s+TransformStream\s*\(/,67,102,14.1],['text-encoder','TextEncoder','web-api',/\bnew\s+TextEncoder\s*\(/,38,19,10.1],
      ['crypto-subtle','Web Crypto','web-api',/crypto\.subtle\b/,37,34,11],['custom-elements','Custom Elements','web-api',/customElements\.define\s*\(/,54,63,10.1],['shadow-dom','Shadow DOM','web-api',/\.attachShadow\s*\(/,53,63,10],['element-animate','Web Animations API','web-api',/\.animate\s*\(/,36,48,13.1],
      ['scroll-into-view','ScrollIntoView options','web-api',/scrollIntoView\s*\(\s*\{/,61,36,14],['match-media','matchMedia','web-api',/\bmatchMedia\s*\(/,9,6,5.1],['visual-viewport','Visual Viewport API','web-api',/visualViewport\b/,61,91,13],['network-information','Network Information API','web-api',/navigator\.connection\b/,61,999,999],
      ['device-memory','Device Memory API','web-api',/navigator\.deviceMemory\b/,63,999,999],['hardware-concurrency','Hardware concurrency','web-api',/navigator\.hardwareConcurrency\b/,37,48,10.1],['vibration','Vibration API','web-api',/navigator\.vibrate\s*\(/,32,16,999],['gamepad','Gamepad API','web-api',/navigator\.getGamepads\s*\(/,35,29,10.1],
      ['css-grid','CSS Grid','css',/display\s*:\s*grid\b/i,57,52,10.1],['css-flex-gap','Flexbox gap','css',/\bgap\s*:\s*[^;]+/i,84,63,14.1],['css-logical','CSS logical properties','css',/(?:margin|padding|inset)-(?:inline|block)/i,87,66,14.1],['css-clamp','CSS clamp()','css',/\bclamp\s*\(/i,79,75,13.1],
      ['css-minmax','CSS minmax()','css',/\bminmax\s*\(/i,57,52,10.1],['css-aspect-ratio','CSS aspect-ratio','css',/aspect-ratio\s*:/i,88,89,15],['css-sticky','CSS sticky positioning','css',/position\s*:\s*sticky/i,56,32,7.1],['css-scroll-snap','CSS scroll snap','css',/scroll-snap-(?:type|align)\s*:/i,69,68,11],
      ['css-variables','CSS custom properties','css',/var\s*\(\s*--/i,49,31,9.1],['css-masks','CSS masks','css',/(?:-webkit-)?mask(?:-image)?\s*:/i,120,53,15.4],['css-overscroll','CSS overscroll-behavior','css',/overscroll-behavior\s*:/i,63,59,16],['css-accent-color','CSS accent-color','css',/accent-color\s*:/i,93,92,15.4],
      ['css-cascade-layers','CSS cascade layers','css',/@layer\b/i,99,97,15.4],['css-is','CSS :is()','css',/:is\s*\(/i,88,78,14],['css-where','CSS :where()','css',/:where\s*\(/i,88,78,14],['css-any-link','CSS :any-link','css',/:any-link\b/i,65,50,9],
      ['css-marker','CSS ::marker','css',/::marker\b/i,86,68,11.1],['css-placeholder','CSS ::placeholder','css',/::placeholder\b/i,57,51,10.1],['css-motion-path','CSS motion path','css',/offset-path\s*:/i,55,72,15.4],['css-text-wrap-balance','CSS text-wrap balance','css',/text-wrap\s*:\s*balance/i,114,121,17.5],
      ['css-dvh','Dynamic viewport units','css',/\b\d+(?:dvh|dvw|svh|lvh)\b/i,108,101,15.4],['css-lch','CSS LCH colors','css',/\b(?:ok)?lch\s*\(/i,111,113,15],['css-relative-color','CSS relative colors','css',/\b(?:rgb|hsl)\s*\(\s*from\b/i,119,128,16.4],['css-scope','CSS @scope','css',/@scope\b/i,118,146,17.4],
      ['async-await','Async functions','javascript',/\basync\s+(?:function|\([^)]*\)\s*=>)|\bawait\s+/m,55,52,11],['modules','JavaScript modules','javascript',/<script[^>]+type=["']module["']/i,61,60,10.1],['dynamic-import','Dynamic import','javascript',/\bimport\s*\(/,63,67,11.1],['private-fields','Private class fields','javascript',/\bclass\s+\w+[\s\S]{0,200}?#[A-Za-z_$]/,74,90,14.1],
      ['logical-assignment','Logical assignment operators','javascript',/&&=|\|\|=|\?\?=/,85,79,14],['numeric-separator','Numeric separators','javascript',/\b\d[\d_]*_\d[\d_]*\b/,75,70,13],['object-from-entries','Object.fromEntries()','javascript',/Object\.fromEntries\s*\(/,73,63,12.1],['global-this','globalThis','javascript',/\bglobalThis\b/,71,65,12.1],
      ['promise-any','Promise.any()','javascript',/Promise\.any\s*\(/,85,79,14],['weak-ref','WeakRef','javascript',/\bnew\s+WeakRef\s*\(/,84,79,14.1],['array-flat','Array.prototype.flat()','javascript',/\.flat(?:Map)?\s*\(/,69,62,12],['string-replace-all','String.replaceAll()','javascript',/\.replaceAll\s*\(/,85,77,13.1],
      ['intl-segmenter','Intl.Segmenter','javascript',/\bnew\s+Intl\.Segmenter\s*\(/,87,125,14.1],['intl-list-format','Intl.ListFormat','javascript',/\bnew\s+Intl\.ListFormat\s*\(/,72,78,14.1],['top-level-await','Top-level await','javascript',/^\s*await\s+/m,89,89,15],['regexp-lookbehind','RegExp lookbehind','javascript',/\(\?<=[^)]|\(\?<![^)]/,62,78,16.4],
    ] as const
  ).map(([id, feature, kind, pattern, chrome, firefox, safari]) => ({ id, feature, kind, pattern, minimums: { Chrome: chrome, Edge: chrome, Firefox: firefox, Safari: safari, 'Chrome Android': chrome, 'Safari iOS': safari }, recommendation: `Feature-detect or compile ${feature} when supporting older browser targets.` })),
] as const;
