import type { ProjectFile } from './types';
import { API_ROUTE_RULES } from './api-knowledge';
import { isProjectEvidenceFile } from './project-scope';

export type SymbolKind = 'function' | 'class' | 'interface' | 'type' | 'enum' | 'component' | 'export';
export interface CodeSymbol { name: string; kind: SymbolKind; file: string; line: number; exported: boolean; }
export interface DependencyEdge { from: string; to: string; kind: 'import' | 'require' | 'dynamic-import'; }
export interface ApiEndpoint { method: string; route: string; file: string; line: number; framework?: string; confidence?: number; }
export interface CodeQualitySignals { largeFiles: Array<{ file: string; lines: number }>; largeFunctions: Array<{ file: string; name: string; line: number; lines?: number }>; todoCount: number; fixmeCount: number; circularDependencies: string[][]; }
export interface CodeIntelligence { filesAnalyzed: number; symbols: CodeSymbol[]; dependencyEdges: DependencyEdge[]; apiEndpoints: ApiEndpoint[]; entryPoints: string[]; architectureAreas: Record<string, string[]>; quality: CodeQualitySignals; frameworksCovered?: string[]; }

const SOURCE_RE = /\.(tsx?|jsx?|mjs|cjs|py|java|kt|kts|go|rs|php|rb|ex|exs|dart|swift|scala|cs|c|cc|cpp|h|hpp|zig|lua|jl|r|cr|nim|sol|v|erl|hrl)$/i;
const IMPORT_RE = /(?:import\s+(?:[\s\S]*?\s+from\s+)?|export\s+(?:[\s\S]*?\s+from\s+)?|require\s*\(|import\s*\()(['"])([^'"]+)\1/g;
const SYMBOL_PATTERNS: Array<[SymbolKind, RegExp]> = [
  ['function', /\b(?:async\s+)?function\s+([A-Za-z_$][\w$]*)/g], ['class', /\bclass\s+([A-Za-z_$][\w$]*)/g], ['interface', /\binterface\s+([A-Za-z_$][\w$]*)/g], ['type', /\btype\s+([A-Za-z_$][\w$]*)\s*=/g], ['enum', /\benum\s+([A-Za-z_$][\w$]*)/g], ['component', /\b(?:const|function)\s+([A-Z][A-Za-z0-9_$]*)/g],
];
function lineAt(source: string, offset: number): number { return source.slice(0, offset).split('\n').length; }
function isSource(file: ProjectFile): boolean { return !file.isDirectory && SOURCE_RE.test(file.path) && isProjectEvidenceFile(file); }
function normalizeRoute(route: string): string { const value = route.startsWith('/') ? route : `/${route}`; return value.replace(/\[(?:\.\.\.)?([^\]]+)\]/g, ':$1').replace(/\/+/g, '/'); }
function functionLines(source: string, offset: number): number | undefined { const open = source.indexOf('{', offset); if (open < 0 || open - offset > 300) return undefined; let depth = 0; for (let i = open; i < source.length; i++) { if (source[i] === '{') depth++; else if (source[i] === '}' && --depth === 0) return lineAt(source, i) - lineAt(source, offset) + 1; } return undefined; }
function fileRoutes(file: ProjectFile, source: string): ApiEndpoint[] { const path = file.path.replace(/\\/g, '/'); const next = /(?:^|\/)app\/api\/(.+)\/route\.[cm]?[jt]s$/.exec(path); if (next) { const route = normalizeRoute('/api/' + next[1].replace(/\/(?:route)$/, '')); return [...source.matchAll(/\bexport\s+(?:async\s+)?function\s+(GET|POST|PUT|PATCH|DELETE|OPTIONS|HEAD)\b/g)].map((match) => ({ method: match[1], route, file: file.path, line: lineAt(source, match.index), framework: 'Next.js App Router', confidence: 98 })); } const pages = /(?:^|\/)pages\/api\/(.+)\.[cm]?[jt]s$/.exec(path); return pages ? [{ method: 'ROUTE', route: normalizeRoute('/api/' + pages[1].replace(/\/index$/, '')), file: file.path, line: 1, framework: 'Next.js Pages Router', confidence: 94 }] : []; }
function normalizeTarget(from: string, target: string, files: ProjectFile[]): string | undefined {
  if (!target.startsWith('.')) return undefined; const base = from.split('/'); base.pop(); const raw = [...base, ...target.split('/')]; const parts: string[] = [];
  for (const part of raw) { if (part === '..') parts.pop(); else if (part !== '.') parts.push(part); }
  const candidates = [parts.join('/'), ...['.ts','.tsx','.js','.jsx','.mjs','.cjs'].map((ext) => `${parts.join('/')}${ext}`), ...['index.ts','index.tsx','index.js','index.jsx'].map((name) => `${parts.join('/')}/${name}`)];
  return files.find((file) => candidates.includes(file.path) && !file.isDirectory)?.path;
}
function areaFor(file: string): string { const lower = file.toLowerCase(); if (/\b(api|route|routes|controller|controllers|server)\b/.test(lower)) return 'API'; if (/\b(component|components|pages|views|ui)\b/.test(lower)) return 'Frontend'; if (/\b(test|tests|spec|__tests__)\b/.test(lower)) return 'Testing'; if (/\b(config|configs|configuration)\b/.test(lower)) return 'Configuration'; if (/\b(lib|utils|utility|helpers|shared)\b/.test(lower)) return 'Shared'; if (/\b(service|services|domain|repository|repositories|backend)\b/.test(lower)) return 'Backend'; return 'Core'; }
function findCycles(edges: DependencyEdge[]): string[][] { const graph = new Map<string, string[]>(); for (const edge of edges) { if (!graph.has(edge.from)) graph.set(edge.from, []); if (!graph.has(edge.to)) graph.set(edge.to, []); const targets = graph.get(edge.from)!; if (!targets.includes(edge.to)) targets.push(edge.to); } const cycles: string[][] = []; const seen = new Set<string>(); const visit = (start: string, node: string, path: string[]) => { for (const target of graph.get(node) ?? []) { if (target === start && path.length > 1) { const cycle = [...path]; const key = [...cycle].sort().join('|'); if (!seen.has(key)) { seen.add(key); cycles.push(cycle); } } else if (!path.includes(target) && path.length < 8) visit(start, target, [...path, target]); } }; for (const node of graph.keys()) visit(node, node, [node]); return cycles.slice(0, 20); }
export function detectCodeIntelligence(files: ProjectFile[]): CodeIntelligence {
  const sourceFiles = files.filter(isSource); const symbols: CodeSymbol[] = []; const dependencyEdges: DependencyEdge[] = []; const apiEndpoints: ApiEndpoint[] = []; const architectureAreas: Record<string, string[]> = {}; const largeFiles: Array<{ file: string; lines: number }> = []; const largeFunctions: Array<{ file: string; name: string; line: number; lines?: number }> = []; let todoCount = 0; let fixmeCount = 0;
  for (const file of sourceFiles) {
    const source = file.content ?? ''; const lines = source ? source.split('\n').length : 0; const area = areaFor(file.path); (architectureAreas[area] ??= []).push(file.path); if (lines >= 500) largeFiles.push({ file: file.path, lines });
    for (const [kind, regex] of SYMBOL_PATTERNS) { regex.lastIndex = 0; let match: RegExpExecArray | null; while ((match = regex.exec(source))) { const name = match[1]; if (kind === 'component' && symbols.some((s) => s.name === name && s.file === file.path)) continue; const before = source.slice(Math.max(0, match.index - 30), match.index); const exported = /\bexport\s*$/.test(before) || new RegExp(`\\bexport\\s+(?:default\\s+)?(?:async\\s+)?(?:function|class|const|interface|type|enum)\\s+${name}`).test(source); symbols.push({ name, kind, file: file.path, line: lineAt(source, match.index), exported }); if (kind === 'function') { const span = functionLines(source, match.index); if (span && span >= 80) largeFunctions.push({ file: file.path, name, line: lineAt(source, match.index), lines: span }); } } }
    IMPORT_RE.lastIndex = 0; let importMatch: RegExpExecArray | null; while ((importMatch = IMPORT_RE.exec(source))) { const target = normalizeTarget(file.path, importMatch[2], files); if (target) dependencyEdges.push({ from: file.path, to: target, kind: source.slice(importMatch.index, importMatch.index + 10).includes('require') ? 'require' : source.slice(importMatch.index, importMatch.index + 10).includes('import(') ? 'dynamic-import' : 'import' }); }
    apiEndpoints.push(...fileRoutes(file, source));
    for (const rule of API_ROUTE_RULES) { const regex = new RegExp(rule.pattern.source, rule.pattern.flags); let match: RegExpExecArray | null; while ((match = regex.exec(source))) { const route = match[1]; if (!route) continue; apiEndpoints.push({ method: rule.method, route: normalizeRoute(route), file: file.path, line: lineAt(source, match.index), framework: rule.framework, confidence: rule.confidence }); } }
    todoCount += (source.match(/\bTODO\b/gi) ?? []).length; fixmeCount += (source.match(/\bFIXME\b/gi) ?? []).length;
  }
  const uniqueEdges = Array.from(new Map(dependencyEdges.map((edge) => [`${edge.from}|${edge.to}|${edge.kind}`, edge])).values());
  const entryPoints = sourceFiles.filter((file) => /(^|\/)(main|index|app|server|cli|start)\.(tsx?|jsx?|mjs|cjs|py|go|rs|java|kt)$/i.test(file.path)).map((file) => file.path).slice(0, 20); const circularDependencies = findCycles(uniqueEdges);
  const uniqueEndpoints = Array.from(new Map(apiEndpoints.map((endpoint) => [`${endpoint.method}|${endpoint.route}|${endpoint.file}`, endpoint])).values());
  return { filesAnalyzed: sourceFiles.length, symbols: symbols.slice(0, 2000), dependencyEdges: uniqueEdges.slice(0, 3000), apiEndpoints: uniqueEndpoints.slice(0, 500), entryPoints, architectureAreas, quality: { largeFiles: largeFiles.slice(0, 50), largeFunctions: largeFunctions.slice(0, 50), todoCount, fixmeCount, circularDependencies }, frameworksCovered: [...new Set(uniqueEndpoints.map((endpoint) => endpoint.framework).filter((item): item is string => Boolean(item)))] };
}
