import type { TechnologyDefinition } from './technology-registry';

/** Phase 2 cross-platform marker catalog. Signals are exact files, paths, or declared packages. */
export const PLATFORM_KNOWLEDGE: readonly TechnologyDefinition[] = [
  { id: "pm2-npm", name: "npm", kind: "package-manager", files: ["package-lock.json"] },
  { id: "pm2-pnpm", name: "pnpm", kind: "package-manager", files: ["pnpm-lock.yaml"] },
  { id: "pm2-yarn", name: "Yarn", kind: "package-manager", files: ["yarn.lock"] },
  { id: "pm2-bun", name: "Bun", kind: "package-manager", files: ["bun.lock"] },
  { id: "pm2-pip", name: "pip", kind: "package-manager", files: ["requirements.txt"] },
  { id: "pm2-poetry", name: "Poetry", kind: "package-manager", files: ["poetry.lock"] },
  { id: "pm2-pdm", name: "PDM", kind: "package-manager", files: ["pdm.lock"] },
  { id: "pm2-pipenv", name: "Pipenv", kind: "package-manager", files: ["Pipfile.lock"] },
  { id: "pm2-uv", name: "uv", kind: "package-manager", files: ["uv.lock"] },
  { id: "pm2-hatch", name: "Hatch", kind: "package-manager", files: ["hatch.toml"] },
  { id: "pm2-conda", name: "Conda", kind: "package-manager", files: ["environment.yml"] },
  { id: "pm2-mamba", name: "Mamba", kind: "package-manager", files: ["conda-lock.yml"] },
  { id: "pm2-cargo", name: "Cargo", kind: "package-manager", files: ["Cargo.lock"] },
  { id: "pm2-go-modules", name: "Go Modules", kind: "package-manager", files: ["go.sum"] },
  { id: "pm2-maven", name: "Maven", kind: "package-manager", files: ["pom.xml"] },
  { id: "pm2-gradle", name: "Gradle", kind: "package-manager", files: ["gradle.lockfile"] },
  { id: "pm2-composer", name: "Composer", kind: "package-manager", files: ["composer.lock"] },
  { id: "pm2-bundler", name: "Bundler", kind: "package-manager", files: ["Gemfile.lock"] },
  { id: "pm2-mix", name: "Mix", kind: "package-manager", files: ["mix.lock"] },
  { id: "pm2-dart-pub", name: "Dart Pub", kind: "package-manager", files: ["pubspec.lock"] },
  { id: "pm2-swift-package-manager", name: "Swift Package Manager", kind: "package-manager", files: ["Package.resolved"] },
  { id: "pm2-sbt", name: "sbt", kind: "package-manager", files: ["build.sbt"] },
  { id: "pm2-nuget", name: "NuGet", kind: "package-manager", files: ["packages.lock.json"] },
  { id: "pm2-cocoapods", name: "CocoaPods", kind: "package-manager", files: ["Podfile.lock"] },
  { id: "pm2-carthage", name: "Carthage", kind: "package-manager", files: ["Cartfile.resolved"] },
  { id: "pm2-homebrew", name: "Homebrew", kind: "package-manager", files: ["Brewfile"] },
  { id: "pm2-nix", name: "Nix", kind: "package-manager", files: ["flake.lock"] },
  { id: "pm2-renovate", name: "Renovate", kind: "package-manager", files: ["renovate.json"] },
  { id: "pm2-dependabot", name: "Dependabot", kind: "package-manager", pathPatterns: [/(^|\/)\.github\/dependabot\.ya?ml$/i] },
  { id: "pm2-lerna", name: "Lerna", kind: "package-manager", files: ["lerna.json"] },
  { id: "pm2-rush", name: "Rush", kind: "package-manager", files: ["rush.json"] },
  { id: "pm2-nx", name: "Nx", kind: "package-manager", files: ["nx.json"] },
  { id: "pm2-turborepo", name: "Turborepo", kind: "package-manager", files: ["turbo.json"] },
  { id: "pm2-bower", name: "Bower", kind: "package-manager", files: ["bower.json"] },
  { id: "pm2-jspm", name: "JSPM", kind: "package-manager", files: ["jspm.json"] },
  { id: "pm2-conan", name: "Conan", kind: "package-manager", files: ["conanfile.txt"] },
  { id: "pm2-vcpkg", name: "vcpkg", kind: "package-manager", files: ["vcpkg.json"] },
  { id: "pm2-hunter", name: "Hunter", kind: "package-manager", files: ["HunterGate.cmake"] },
  { id: "pm2-cpan", name: "CPAN", kind: "package-manager", files: ["cpanfile"] },
  { id: "pm2-rubygems", name: "RubyGems", kind: "package-manager", files: ["gemspec"] },
  { id: "build2-vite", name: "Vite", kind: "build-tool", dependencies: ["vite"] },
  { id: "build2-webpack", name: "Webpack", kind: "build-tool", dependencies: ["webpack"] },
  { id: "build2-rollup", name: "Rollup", kind: "build-tool", dependencies: ["rollup"] },
  { id: "build2-esbuild", name: "esbuild", kind: "build-tool", dependencies: ["esbuild"] },
  { id: "build2-parcel", name: "Parcel", kind: "build-tool", dependencies: ["parcel"] },
  { id: "build2-rspack", name: "Rspack", kind: "build-tool", dependencies: ["@rspack/core"] },
  { id: "build2-turbopack", name: "Turbopack", kind: "build-tool", manifestPatterns: [{ files: ["package.json"], pattern: /--turbopack\b/ }] },
  { id: "build2-babel", name: "Babel", kind: "build-tool", dependencies: ["@babel/core"] },
  { id: "build2-swc", name: "SWC", kind: "build-tool", dependencies: ["@swc/core"] },
  { id: "build2-typescript", name: "TypeScript", kind: "build-tool", files: ["tsconfig.json"] },
  { id: "build2-tsup", name: "tsup", kind: "build-tool", dependencies: ["tsup"] },
  { id: "build2-unbuild", name: "Unbuild", kind: "build-tool", dependencies: ["unbuild"] },
  { id: "build2-gulp", name: "Gulp", kind: "build-tool", dependencies: ["gulp"] },
  { id: "build2-grunt", name: "Grunt", kind: "build-tool", dependencies: ["grunt"] },
  { id: "build2-broccoli", name: "Broccoli", kind: "build-tool", dependencies: ["broccoli"] },
  { id: "build2-snowpack", name: "Snowpack", kind: "build-tool", dependencies: ["snowpack"] },
  { id: "build2-rome", name: "Rome", kind: "build-tool", dependencies: ["rome"] },
  { id: "build2-biome", name: "Biome", kind: "build-tool", dependencies: ["@biomejs/biome"] },
  { id: "build2-angular-cli", name: "Angular CLI", kind: "build-tool", dependencies: ["@angular/cli"] },
  { id: "build2-create-react-app", name: "Create React App", kind: "build-tool", dependencies: ["react-scripts"] },
  { id: "build2-vue-cli", name: "Vue CLI", kind: "build-tool", dependencies: ["@vue/cli-service"] },
  { id: "build2-sveltekit", name: "SvelteKit", kind: "build-tool", dependencies: ["@sveltejs/kit"] },
  { id: "build2-astro", name: "Astro", kind: "build-tool", dependencies: ["astro"] },
  { id: "build2-gatsby", name: "Gatsby", kind: "build-tool", dependencies: ["gatsby"] },
  { id: "build2-next-js", name: "Next.js", kind: "build-tool", dependencies: ["next"] },
  { id: "build2-nuxt", name: "Nuxt", kind: "build-tool", dependencies: ["nuxt"] },
  { id: "build2-metro", name: "Metro", kind: "build-tool", dependencies: ["metro"] },
  { id: "build2-expo-cli", name: "Expo CLI", kind: "build-tool", dependencies: ["expo"] },
  { id: "build2-electron-forge", name: "Electron Forge", kind: "build-tool", dependencies: ["@electron-forge/cli"] },
  { id: "build2-electron-builder", name: "Electron Builder", kind: "build-tool", dependencies: ["electron-builder"] },
  { id: "build2-tauri-cli", name: "Tauri CLI", kind: "build-tool", dependencies: ["@tauri-apps/cli"] },
  { id: "build2-cargo", name: "Cargo", kind: "build-tool", files: ["Cargo.toml"] },
  { id: "build2-rustc", name: "rustc", kind: "build-tool", files: ["rust-toolchain.toml"] },
  { id: "build2-maven", name: "Maven", kind: "build-tool", files: ["pom.xml"] },
  { id: "build2-gradle", name: "Gradle", kind: "build-tool", files: ["build.gradle"] },
  { id: "build2-ant", name: "Ant", kind: "build-tool", files: ["build.xml"] },
  { id: "build2-sbt", name: "sbt", kind: "build-tool", files: ["build.sbt"] },
  { id: "build2-mill", name: "Mill", kind: "build-tool", files: ["build.sc"] },
  { id: "build2-bazel", name: "Bazel", kind: "build-tool", files: ["WORKSPACE"] },
  { id: "build2-buck", name: "Buck", kind: "build-tool", files: [".buckconfig"] },
  { id: "build2-pants", name: "Pants", kind: "build-tool", files: ["pants.toml"] },
  { id: "build2-cmake", name: "CMake", kind: "build-tool", files: ["CMakeLists.txt"] },
  { id: "build2-meson", name: "Meson", kind: "build-tool", files: ["meson.build"] },
  { id: "build2-ninja", name: "Ninja", kind: "build-tool", files: ["build.ninja"] },
  { id: "build2-make", name: "Make", kind: "build-tool", files: ["Makefile"] },
  { id: "build2-autotools", name: "Autotools", kind: "build-tool", files: ["configure.ac"] },
  { id: "build2-msbuild", name: "MSBuild", kind: "build-tool", pathPatterns: [/\.sln$/i] },
  { id: "build2-xcode", name: "Xcode", kind: "build-tool", pathPatterns: [/\.xcodeproj\/project\.pbxproj$/i] },
  { id: "build2-swiftpm", name: "SwiftPM", kind: "build-tool", files: ["Package.swift"] },
  { id: "build2-go-build", name: "Go Build", kind: "build-tool", files: ["go.mod"] },
  { id: "build2-python-build", name: "Python Build", kind: "build-tool", files: ["pyproject.toml"] },
  { id: "build2-setuptools", name: "Setuptools", kind: "build-tool", files: ["setup.py"] },
  { id: "build2-poetry", name: "Poetry", kind: "build-tool", files: ["poetry.lock"] },
  { id: "build2-hatch", name: "Hatch", kind: "build-tool", files: ["hatch.toml"] },
  { id: "build2-pyinstaller", name: "PyInstaller", kind: "build-tool", pathPatterns: [/\.spec$/i] },
  { id: "build2-composer", name: "Composer", kind: "build-tool", files: ["composer.json"] },
  { id: "build2-mix", name: "Mix", kind: "build-tool", files: ["mix.exs"] },
  { id: "build2-dart-build", name: "Dart Build", kind: "build-tool", files: ["pubspec.yaml"] },
  { id: "build2-hardhat", name: "Hardhat", kind: "build-tool", files: ["hardhat.config.ts"] },
  { id: "build2-foundry", name: "Foundry", kind: "build-tool", files: ["foundry.toml"] },
  { id: "runtime2-node-js", name: "Node.js", kind: "runtime", files: ["package.json"] },
  { id: "runtime2-bun", name: "Bun", kind: "runtime", files: ["bun.lock"] },
  { id: "runtime2-deno", name: "Deno", kind: "runtime", files: ["deno.json"] },
  { id: "runtime2-python", name: "Python", kind: "runtime", files: ["pyproject.toml"] },
  { id: "runtime2-jvm", name: "JVM", kind: "runtime", files: ["pom.xml"] },
  { id: "runtime2-go", name: "Go", kind: "runtime", files: ["go.mod"] },
  { id: "runtime2-rust", name: "Rust", kind: "runtime", files: ["Cargo.toml"] },
  { id: "runtime2-ruby", name: "Ruby", kind: "runtime", files: ["Gemfile"] },
  { id: "runtime2-beam", name: "BEAM", kind: "runtime", files: ["mix.exs"] },
  { id: "runtime2-dart", name: "Dart", kind: "runtime", files: ["pubspec.yaml"] },
  { id: "runtime2-swift", name: "Swift", kind: "runtime", files: ["Package.swift"] },
  { id: "runtime2-net", name: ".NET", kind: "runtime", pathPatterns: [/\.csproj$/i] },
  { id: "runtime2-php", name: "PHP", kind: "runtime", files: ["composer.json"] },
  { id: "runtime2-perl", name: "Perl", kind: "runtime", files: ["cpanfile"] },
  { id: "runtime2-lua", name: "Lua", kind: "runtime", files: [".luacheckrc"] },
  { id: "runtime2-julia", name: "Julia", kind: "runtime", files: ["Project.toml"] },
  { id: "runtime2-r", name: "R", kind: "runtime", files: ["renv.lock"] },
  { id: "runtime2-crystal", name: "Crystal", kind: "runtime", files: ["shard.yml"] },
  { id: "runtime2-nim", name: "Nim", kind: "runtime", pathPatterns: [/\.nimble$/i] },
  { id: "runtime2-v", name: "V", kind: "runtime", files: ["v.mod"] },
  { id: "runtime2-erlang", name: "Erlang", kind: "runtime", files: ["rebar.config"] },
  { id: "runtime2-browser", name: "Browser", kind: "runtime", files: ["index.html"] },
  { id: "runtime2-cloudflare-workers", name: "Cloudflare Workers", kind: "runtime", files: ["wrangler.toml"] },
  { id: "runtime2-wasmtime", name: "Wasmtime", kind: "runtime", files: ["wasmtime.toml"] },
  { id: "runtime2-wasi", name: "WASI", kind: "runtime", files: ["wit.toml"] },
  { id: "db2-postgresql", name: "PostgreSQL", kind: "database", dependencies: ["pg"] },
  { id: "db2-mysql", name: "MySQL", kind: "database", dependencies: ["mysql2"] },
  { id: "db2-mariadb", name: "MariaDB", kind: "database", dependencies: ["mariadb"] },
  { id: "db2-sqlite", name: "SQLite", kind: "database", dependencies: ["better-sqlite3"] },
  { id: "db2-mongodb", name: "MongoDB", kind: "database", dependencies: ["mongodb"] },
  { id: "db2-redis", name: "Redis", kind: "database", dependencies: ["redis"] },
  { id: "db2-cassandra", name: "Cassandra", kind: "database", dependencies: ["cassandra-driver"] },
  { id: "db2-dynamodb", name: "DynamoDB", kind: "database", dependencies: ["@aws-sdk/client-dynamodb"] },
  { id: "db2-elasticsearch", name: "Elasticsearch", kind: "database", dependencies: ["@elastic/elasticsearch"] },
  { id: "db2-opensearch", name: "OpenSearch", kind: "database", dependencies: ["@opensearch-project/opensearch"] },
  { id: "db2-firebase", name: "Firebase", kind: "database", dependencies: ["firebase"] },
  { id: "db2-supabase", name: "Supabase", kind: "database", dependencies: ["@supabase/supabase-js"] },
  { id: "db2-cockroachdb", name: "CockroachDB", kind: "database", files: ["cockroach.yml"] },
  { id: "db2-neo4j", name: "Neo4j", kind: "database", dependencies: ["neo4j-driver"] },
  { id: "db2-couchdb", name: "CouchDB", kind: "database", dependencies: ["nano"] },
  { id: "db2-pouchdb", name: "PouchDB", kind: "database", dependencies: ["pouchdb"] },
  { id: "db2-leveldb", name: "LevelDB", kind: "database", dependencies: ["level"] },
  { id: "db2-lmdb", name: "LMDB", kind: "database", dependencies: ["lmdb"] },
  { id: "db2-duckdb", name: "DuckDB", kind: "database", dependencies: ["duckdb"] },
  { id: "db2-clickhouse", name: "ClickHouse", kind: "database", dependencies: ["@clickhouse/client"] },
  { id: "db2-influxdb", name: "InfluxDB", kind: "database", dependencies: ["@influxdata/influxdb-client"] },
  { id: "db2-pinecone", name: "Pinecone", kind: "database", dependencies: ["@pinecone-database/pinecone"] },
  { id: "db2-qdrant", name: "Qdrant", kind: "database", dependencies: ["@qdrant/js-client-rest"] },
  { id: "db2-weaviate", name: "Weaviate", kind: "database", dependencies: ["weaviate-client"] },
  { id: "db2-milvus", name: "Milvus", kind: "database", dependencies: ["@zilliz/milvus2-sdk-node"] },
  { id: "db2-chroma", name: "Chroma", kind: "database", dependencies: ["chromadb"] },
  { id: "db2-oracle-database", name: "Oracle Database", kind: "database", dependencies: ["oracledb"] },
  { id: "db2-microsoft-sql-server", name: "Microsoft SQL Server", kind: "database", dependencies: ["mssql"] },
  { id: "db2-ibm-db2", name: "IBM Db2", kind: "database", dependencies: ["ibm_db"] },
  { id: "db2-snowflake", name: "Snowflake", kind: "database", dependencies: ["snowflake-sdk"] },
  { id: "db2-bigquery", name: "BigQuery", kind: "database", dependencies: ["@google-cloud/bigquery"] },
  { id: "db2-redshift", name: "Redshift", kind: "database", dependencies: ["@aws-sdk/client-redshift"] },
  { id: "db2-databricks", name: "Databricks", kind: "database", dependencies: ["@databricks/sql"] },
  { id: "db2-timescaledb", name: "TimescaleDB", kind: "database", files: ["timescaledb.conf"] },
  { id: "db2-scylladb", name: "ScyllaDB", kind: "database", files: ["scylla.yaml"] },
  { id: "db2-fauna", name: "Fauna", kind: "database", dependencies: ["faunadb"] },
  { id: "db2-planetscale", name: "PlanetScale", kind: "database", dependencies: ["@planetscale/database"] },
  { id: "db2-neon", name: "Neon", kind: "database", dependencies: ["@neondatabase/serverless"] },
  { id: "db2-turso", name: "Turso", kind: "database", dependencies: ["@libsql/client"] },
  { id: "db2-tidb", name: "TiDB", kind: "database", files: ["tidb.toml"] },
  { id: "db2-yugabytedb", name: "YugabyteDB", kind: "database", files: ["yugabyted.conf"] },
  { id: "db2-surrealdb", name: "SurrealDB", kind: "database", dependencies: ["surrealdb"] },
  { id: "db2-arangodb", name: "ArangoDB", kind: "database", dependencies: ["arangojs"] },
  { id: "db2-rethinkdb", name: "RethinkDB", kind: "database", dependencies: ["rethinkdb"] },
  { id: "db2-rocksdb", name: "RocksDB", kind: "database", dependencies: ["rocksdb"] },
  { id: "db2-memcached", name: "Memcached", kind: "database", dependencies: ["memcached"] },
  { id: "db2-upstash", name: "Upstash", kind: "database", dependencies: ["@upstash/redis"] },
  { id: "db2-meilisearch", name: "Meilisearch", kind: "database", dependencies: ["meilisearch"] },
  { id: "db2-typesense", name: "Typesense", kind: "database", dependencies: ["typesense"] },
  { id: "db2-algolia", name: "Algolia", kind: "database", dependencies: ["algoliasearch"] },
  { id: "test2-vitest", name: "Vitest", kind: "testing", dependencies: ["vitest"] },
  { id: "test2-jest", name: "Jest", kind: "testing", dependencies: ["jest"] },
  { id: "test2-playwright", name: "Playwright", kind: "testing", dependencies: ["@playwright/test"] },
  { id: "test2-cypress", name: "Cypress", kind: "testing", dependencies: ["cypress"] },
  { id: "test2-mocha", name: "Mocha", kind: "testing", dependencies: ["mocha"] },
  { id: "test2-jasmine", name: "Jasmine", kind: "testing", dependencies: ["jasmine"] },
  { id: "test2-ava", name: "AVA", kind: "testing", dependencies: ["ava"] },
  { id: "test2-tape", name: "Tape", kind: "testing", dependencies: ["tape"] },
  { id: "test2-tap", name: "Tap", kind: "testing", dependencies: ["tap"] },
  { id: "test2-qunit", name: "QUnit", kind: "testing", dependencies: ["qunit"] },
  { id: "test2-testing-library", name: "Testing Library", kind: "testing", dependencies: ["@testing-library/react"] },
  { id: "test2-supertest", name: "Supertest", kind: "testing", dependencies: ["supertest"] },
  { id: "test2-sinon", name: "Sinon", kind: "testing", dependencies: ["sinon"] },
  { id: "test2-msw", name: "MSW", kind: "testing", dependencies: ["msw"] },
  { id: "test2-nock", name: "Nock", kind: "testing", dependencies: ["nock"] },
  { id: "test2-puppeteer", name: "Puppeteer", kind: "testing", dependencies: ["puppeteer"] },
  { id: "test2-webdriverio", name: "WebdriverIO", kind: "testing", dependencies: ["webdriverio"] },
  { id: "test2-selenium", name: "Selenium", kind: "testing", dependencies: ["selenium-webdriver"] },
  { id: "test2-karma", name: "Karma", kind: "testing", dependencies: ["karma"] },
  { id: "test2-nyc", name: "NYC", kind: "testing", dependencies: ["nyc"] },
  { id: "test2-c8", name: "C8", kind: "testing", dependencies: ["c8"] },
  { id: "test2-fast-check", name: "Fast Check", kind: "testing", dependencies: ["fast-check"] },
  { id: "test2-stryker", name: "Stryker", kind: "testing", dependencies: ["@stryker-mutator/core"] },
  { id: "test2-axe", name: "Axe", kind: "testing", dependencies: ["axe-core"] },
  { id: "test2-lighthouse", name: "Lighthouse", kind: "testing", dependencies: ["lighthouse"] },
  { id: "test2-pytest", name: "Pytest", kind: "testing", files: ["pytest.ini"] },
  { id: "test2-unittest", name: "Unittest", kind: "testing", pathPatterns: [/(^|\/)test_.*\.py$/i] },
  { id: "test2-hypothesis", name: "Hypothesis", kind: "testing", files: [".hypothesis"] },
  { id: "test2-nose", name: "Nose", kind: "testing", files: ["nose.cfg"] },
  { id: "test2-tox", name: "tox", kind: "testing", files: ["tox.ini"] },
  { id: "test2-junit", name: "JUnit", kind: "testing", pathPatterns: [/(^|\/)junit-platform\.properties$/i] },
  { id: "test2-testng", name: "TestNG", kind: "testing", files: ["testng.xml"] },
  { id: "test2-mockito", name: "Mockito", kind: "testing", pathPatterns: [/(^|\/)mockito-extensions\//i] },
  { id: "test2-spock", name: "Spock", kind: "testing", files: ["SpockConfig.groovy"] },
  { id: "test2-kotest", name: "Kotest", kind: "testing", pathPatterns: [/(^|\/)kotest\.properties$/i] },
  { id: "test2-rspec", name: "RSpec", kind: "testing", files: [".rspec"] },
  { id: "test2-minitest", name: "Minitest", kind: "testing", pathPatterns: [/(^|\/)test_helper\.rb$/i] },
  { id: "test2-phpunit", name: "PHPUnit", kind: "testing", files: ["phpunit.xml"] },
  { id: "test2-pest", name: "Pest", kind: "testing", files: ["Pest.php"] },
  { id: "test2-exunit", name: "ExUnit", kind: "testing", files: ["test_helper.exs"] },
  { id: "test2-go-test", name: "Go Test", kind: "testing", pathPatterns: [/_test\.go$/i] },
  { id: "test2-cargo-test", name: "Cargo Test", kind: "testing", pathPatterns: [/(^|\/)tests\/.*\.rs$/i] },
  { id: "test2-criterion", name: "Criterion", kind: "testing", files: ["criterion.toml"] },
  { id: "test2-proptest", name: "Proptest", kind: "testing", pathPatterns: [/(^|\/)proptest-regressions\//i] },
  { id: "test2-xctest", name: "XCTest", kind: "testing", pathPatterns: [/Tests\.swift$/i] },
  { id: "test2-dart-test", name: "Dart Test", kind: "testing", pathPatterns: [/(^|\/)test\/.*_test\.dart$/i] },
  { id: "test2-flutter-test", name: "Flutter Test", kind: "testing", pathPatterns: [/(^|\/)integration_test\/.*\.dart$/i] },
  { id: "test2-nunit", name: "NUnit", kind: "testing", pathPatterns: [/\.nunit$/i] },
  { id: "test2-xunit-net", name: "xUnit.net", kind: "testing", files: ["xunit.runner.json"] },
  { id: "test2-mstest", name: "MSTest", kind: "testing", files: [".runsettings"] },
  { id: "test2-catch2", name: "Catch2", kind: "testing", pathPatterns: [/catch2\/catch_/i] },
  { id: "test2-googletest", name: "GoogleTest", kind: "testing", pathPatterns: [/googletest/i] },
  { id: "test2-ctest", name: "CTest", kind: "testing", files: ["CTestTestfile.cmake"] },
  { id: "test2-robot-framework", name: "Robot Framework", kind: "testing", pathPatterns: [/\.robot$/i] },
  { id: "test2-cucumber", name: "Cucumber", kind: "testing", pathPatterns: [/\.feature$/i] },
  { id: "test2-behave", name: "Behave", kind: "testing", files: ["behave.ini"] },
  { id: "test2-k6", name: "k6", kind: "testing", files: ["k6.config.js"] },
  { id: "test2-artillery", name: "Artillery", kind: "testing", files: ["artillery.yml"] },
  { id: "test2-locust", name: "Locust", kind: "testing", files: ["locustfile.py"] },
  { id: "test2-gatling", name: "Gatling", kind: "testing", files: ["gatling.conf"] },
  { id: "cloud2-vercel", name: "Vercel", kind: "cloud", files: ["vercel.json"] },
  { id: "cloud2-netlify", name: "Netlify", kind: "cloud", files: ["netlify.toml"] },
  { id: "cloud2-railway", name: "Railway", kind: "cloud", files: ["railway.json"] },
  { id: "cloud2-fly-io", name: "Fly.io", kind: "cloud", files: ["fly.toml"] },
  { id: "cloud2-render", name: "Render", kind: "cloud", files: ["render.yaml"] },
  { id: "cloud2-cloudflare", name: "Cloudflare", kind: "cloud", files: ["wrangler.toml"] },
  { id: "cloud2-firebase", name: "Firebase", kind: "cloud", files: ["firebase.json"] },
  { id: "cloud2-aws-amplify", name: "AWS Amplify", kind: "cloud", files: ["amplify.yml"] },
  { id: "cloud2-aws-cdk", name: "AWS CDK", kind: "cloud", files: ["cdk.json"] },
  { id: "cloud2-aws-sam", name: "AWS SAM", kind: "cloud", files: ["samconfig.toml"] },
  { id: "cloud2-aws-copilot", name: "AWS Copilot", kind: "cloud", pathPatterns: [/(^|\/)copilot\/.*\/manifest\.ya?ml$/i] },
  { id: "cloud2-aws-elastic-beanstalk", name: "AWS Elastic Beanstalk", kind: "cloud", pathPatterns: [/(^|\/)\.ebextensions\/.*\.config$/i] },
  { id: "cloud2-aws-app-runner", name: "AWS App Runner", kind: "cloud", files: ["apprunner.yaml"] },
  { id: "cloud2-aws-codebuild", name: "AWS CodeBuild", kind: "cloud", files: ["buildspec.yml"] },
  { id: "cloud2-serverless-framework", name: "Serverless Framework", kind: "cloud", files: ["serverless.yml"] },
  { id: "cloud2-sst", name: "SST", kind: "cloud", filePrefixes: ["sst.config."] },
  { id: "cloud2-google-app-engine", name: "Google App Engine", kind: "cloud", manifestPatterns: [{ files: ["app.yaml"], pattern: /^runtime\s*:/m }] },
  { id: "cloud2-google-cloud-build", name: "Google Cloud Build", kind: "cloud", files: ["cloudbuild.yaml"] },
  { id: "cloud2-google-cloud-run", name: "Google Cloud Run", kind: "cloud", manifestPatterns: [{ files: ["service.yaml"], pattern: /serving\.knative\.dev/ }] },
  { id: "cloud2-firebase-functions", name: "Firebase Functions", kind: "cloud", files: ["firebase.json"] },
  { id: "cloud2-azure-functions", name: "Azure Functions", kind: "cloud", files: ["host.json"] },
  { id: "cloud2-azure-static-web-apps", name: "Azure Static Web Apps", kind: "cloud", files: ["staticwebapp.config.json"] },
  { id: "cloud2-azure-app-service", name: "Azure App Service", kind: "cloud", files: ["azure.yaml"] },
  { id: "cloud2-heroku", name: "Heroku", kind: "cloud", files: ["Procfile"] },
  { id: "cloud2-digitalocean-app-platform", name: "DigitalOcean App Platform", kind: "cloud", pathPatterns: [/(^|\/)\.do\/app\.ya?ml$/i] },
  { id: "cloud2-ibm-cloud", name: "IBM Cloud", kind: "cloud", files: ["ibmcloud.yml"] },
  { id: "cloud2-oracle-cloud", name: "Oracle Cloud", kind: "cloud", files: ["func.yaml"] },
  { id: "cloud2-qovery", name: "Qovery", kind: "cloud", files: [".qovery.yml"] },
  { id: "cloud2-koyeb", name: "Koyeb", kind: "cloud", files: ["koyeb.yaml"] },
  { id: "cloud2-northflank", name: "Northflank", kind: "cloud", files: ["northflank.yml"] },
  { id: "cloud2-zeabur", name: "Zeabur", kind: "cloud", files: ["zbpack.json"] },
  { id: "cloud2-deno-deploy", name: "Deno Deploy", kind: "cloud", files: ["deployctl.json"] },
  { id: "cloud2-github-pages", name: "GitHub Pages", kind: "cloud", pathPatterns: [/(^|\/)\.github\/workflows\/[^/]*pages[^/]*\.ya?ml$/i] },
  { id: "cloud2-gitlab-pages", name: "GitLab Pages", kind: "cloud", manifestPatterns: [{ files: [".gitlab-ci.yml"], pattern: /^pages\s*:/m }] },
  { id: "cloud2-surge", name: "Surge", kind: "cloud", dependencies: ["surge"] },
  { id: "cloud2-cloud-foundry", name: "Cloud Foundry", kind: "cloud", manifestPatterns: [{ files: ["manifest.yml"], pattern: /^applications\s*:/m }] },
  { id: "cloud2-openshift", name: "OpenShift", kind: "cloud", manifestPatterns: [{ files: ["template.yaml"], pattern: /template\.openshift\.io/ }] },
  { id: "cloud2-kubernetes", name: "Kubernetes", kind: "cloud", files: ["kustomization.yaml"] },
  { id: "cloud2-helm", name: "Helm", kind: "cloud", files: ["Chart.yaml"] },
  { id: "cloud2-nomad", name: "Nomad", kind: "cloud", pathPatterns: [/\.nomad\.hcl$/i] },
  { id: "ci2-github-actions", name: "GitHub Actions", kind: "ci-cd", pathPatterns: [/(^|\/)\.github\/workflows\/[^/]+\.ya?ml$/i] },
  { id: "ci2-gitlab-ci", name: "GitLab CI", kind: "ci-cd", files: [".gitlab-ci.yml"] },
  { id: "ci2-circleci", name: "CircleCI", kind: "ci-cd", pathPatterns: [/(^|\/)\.circleci\/config\.yml$/i] },
  { id: "ci2-travis-ci", name: "Travis CI", kind: "ci-cd", files: [".travis.yml"] },
  { id: "ci2-jenkins", name: "Jenkins", kind: "ci-cd", files: ["Jenkinsfile"] },
  { id: "ci2-azure-pipelines", name: "Azure Pipelines", kind: "ci-cd", files: ["azure-pipelines.yml"] },
  { id: "ci2-bitbucket-pipelines", name: "Bitbucket Pipelines", kind: "ci-cd", files: ["bitbucket-pipelines.yml"] },
  { id: "ci2-buildkite", name: "Buildkite", kind: "ci-cd", files: [".buildkite/pipeline.yml"] },
  { id: "ci2-drone-ci", name: "Drone CI", kind: "ci-cd", files: [".drone.yml"] },
  { id: "ci2-woodpecker-ci", name: "Woodpecker CI", kind: "ci-cd", files: [".woodpecker.yml"] },
  { id: "ci2-teamcity", name: "TeamCity", kind: "ci-cd", pathPatterns: [/(^|\/)\.teamcity\/settings\.kts$/i] },
  { id: "ci2-appveyor", name: "AppVeyor", kind: "ci-cd", files: ["appveyor.yml"] },
  { id: "ci2-buddy", name: "Buddy", kind: "ci-cd", files: ["buddy.yml"] },
  { id: "ci2-semaphore", name: "Semaphore", kind: "ci-cd", files: [".semaphore/semaphore.yml"] },
  { id: "ci2-codefresh", name: "Codefresh", kind: "ci-cd", files: ["codefresh.yml"] },
  { id: "ci2-harness", name: "Harness", kind: "ci-cd", files: [".harness/pipeline.yaml"] },
  { id: "ci2-tekton", name: "Tekton", kind: "ci-cd", pathPatterns: [/(^|\/)\.tekton\/.*\.ya?ml$/i] },
  { id: "ci2-argo-workflows", name: "Argo Workflows", kind: "ci-cd", files: ["argo-workflow.yaml"] },
  { id: "ci2-concourse", name: "Concourse", kind: "ci-cd", files: ["concourse.yml"] },
  { id: "ci2-bamboo", name: "Bamboo", kind: "ci-cd", files: ["bamboo-specs/bamboo.yml"] },
  { id: "ci2-gocd", name: "GoCD", kind: "ci-cd", files: ["cruise-config.xml"] },
  { id: "ci2-cirrus-ci", name: "Cirrus CI", kind: "ci-cd", files: [".cirrus.yml"] },
  { id: "ci2-earthly", name: "Earthly", kind: "ci-cd", files: ["Earthfile"] },
  { id: "ci2-dagger", name: "Dagger", kind: "ci-cd", files: ["dagger.json"] },
  { id: "ci2-werf", name: "werf", kind: "ci-cd", files: ["werf.yaml"] },
];
