import type { AdditionalLanguage } from './language-knowledge';
import type { V3ExecutionResult } from '../knowledge/v3-types';
export type Severity = 'critical' | 'warning' | 'info';
export type CategoryId = 'runtime' | 'dependencies' | 'configuration' | 'structure' | 'environment' | 'security' | 'deployment' | 'performance';
export type CategoryStatus = 'good' | 'warning' | 'unknown';
export type ProjectType = 'Software Project' | 'Game Project' | 'Media Archive' | 'Document Archive' | 'Unknown Archive';
export interface ProjectClassification { type: ProjectType; isSoftware: boolean; reason: string; }
export type Language = AdditionalLanguage | 'TypeScript' | 'JavaScript' | 'Python' | 'Java' | 'Kotlin' | 'Go' | 'Rust' | 'PHP' | 'Ruby' | 'Elixir' | 'Dart' | 'C' | 'C++' | 'Swift' | 'Scala' | 'C#' | 'Zig' | 'OCaml' | 'Haskell' | 'Lua' | 'Julia' | 'R' | 'Crystal' | 'Nim' | 'Solidity' | 'V' | 'Perl' | 'Erlang' | 'Unknown';
export type Runtime = 'Node.js' | 'Bun' | 'Deno' | 'Python' | 'JVM' | 'Go' | 'Rust' | 'Ruby' | 'BEAM' | 'Dart' | 'Swift' | '.NET' | 'Unknown';
export type PackageManager = 'npm' | 'pnpm' | 'yarn' | 'bun' | 'pip' | 'poetry' | 'pdm' | 'pipenv' | 'uv' | 'hatch' | 'cargo' | 'maven' | 'gradle' | 'composer' | 'go-modules' | 'bundler' | 'mix' | 'pub' | 'swift-package' | 'sbt' | 'nuget' | 'Unknown';
export type BuildTool = 'Vite' | 'Next.js' | 'Nuxt' | 'Astro' | 'Remix' | 'Gatsby' | 'Angular CLI' | 'Create React App' | 'Webpack' | 'esbuild' | 'Rollup' | 'Turbo' | 'Cargo' | 'Maven' | 'Gradle' | 'Flit' | 'Setuptools' | 'PDM' | 'pip' | 'poetry' | 'hatch' | 'CMake' | 'Make' | 'Kbuild' | 'Swift Package Manager' | 'Mix' | 'Pub' | 'turbopack' | 'Unknown';
export type Framework = 'Next.js' | 'Nuxt' | 'Astro' | 'Remix' | 'Gatsby' | 'React' | 'Vue' | 'Angular' | 'Svelte' | 'SvelteKit' | 'Solid' | 'Qwik' | 'Preact' | 'Alpine.js' | 'Lit' | 'Stencil' | 'Express' | 'NestJS' | 'Fastify' | 'Hono' | 'Fiber' | 'Echo' | 'Chi' | 'Django' | 'Flask' | 'FastAPI' | 'Spring Boot' | 'Quarkus' | 'Ktor' | 'Micronaut' | 'Actix' | 'Axum' | 'Rocket' | 'Rails' | 'Sinatra' | 'Phoenix' | 'Vapor' | 'Revel' | 'Play Framework' | 'Laravel' | 'Symfony' | 'Flutter' | 'Gin' | 'Unknown';
export type Database = 'PostgreSQL' | 'MySQL' | 'MariaDB' | 'SQLite' | 'MongoDB' | 'Redis' | 'Cassandra' | 'DynamoDB' | 'Elasticsearch' | 'OpenSearch' | 'Firebase' | 'Supabase' | 'CockroachDB' | 'Neo4j' | 'Detected' | 'Unknown';
export interface ProjectFile { path: string; size: number; isDirectory: boolean; content?: string; }
export interface DetectedFile { path: string; size: number; kind: string; purpose: string; }
export interface DetectionConfidence { language: number; framework: number; runtime: number; packageManager: number; buildTool: number; }
export interface LanguageProfile { language: Language; bytes: number; files: number; percentage: number; }
export type TechnologyKind = 'framework' | 'runtime' | 'database' | 'build-tool' | 'package-manager' | 'library' | 'testing' | 'linting' | 'styling' | 'auth' | 'api' | 'orm' | 'ci-cd' | 'container' | 'cloud' | 'configuration';
export interface TechnologyEvidence { name: string; kind: TechnologyKind; confidence: number; evidence: string[]; version?: string; }
export type DetectionConfidenceLevel = 'confirmed' | 'likely' | 'possible';
export interface DetectionEvidence { kind: 'dependency' | 'file' | 'configuration' | 'manifest' | 'import' | 'content' | 'structure'; source: string; description: string; weight: number; }
export interface TechnologyDetection { id: string; name: string; kind: TechnologyKind; confidence: number; level: DetectionConfidenceLevel; evidence: DetectionEvidence[]; }
export interface ProjectCapability { id: string; name: string; confidence: number; evidence: string[]; }
export interface TechnologyRelationship { from: string; to: string; type: 'runs-on' | 'builds-with' | 'tests-with' | 'stores-in' | 'accesses-with' | 'deploys-to' | 'automated-by' | 'packages-with' | 'authenticates-with' | 'styles-with' | 'managed-by'; confidence: number; evidence: string; }
export interface DependencyItem { name: string; version: string; type: 'runtime' | 'development' | 'peer' | 'optional'; source?: string; }
export interface DependencyRisk { name: string; version: string; source: string; kind: 'wildcard' | 'remote-source' | 'version-conflict'; severity: 'warning' | 'info'; recommendation: string; }
export interface DependencyIntelligence { manager: PackageManager; total: number; runtime: number; development: number; peer: number; optional: number; dependencies: DependencyItem[]; duplicateNames: string[]; versionConflicts: string[]; risks?: DependencyRisk[]; manifestsScanned?: number; healthScore: number; }
export type ArchitectureType = 'Operating System Kernel' | 'SPA' | 'SSR' | 'SSG' | 'API Server' | 'Frontend + Backend' | 'Library' | 'Monorepo' | 'CLI' | 'Mobile App' | 'Desktop App' | 'Microservices' | 'Modular Monolith' | 'Serverless' | 'Event-driven' | 'Clean/Hexagonal' | 'MVC' | 'MVVM' | 'Microfrontend' | 'Plugin Architecture' | 'Offline-first' | 'Background Workers' | 'Containerized Application' | 'Unknown';
export interface ArchitectureIntelligence { primary: ArchitectureType; patterns: ArchitectureType[]; confidence: number; evidence: string[]; }
export interface CodeSymbol { name: string; kind: 'function' | 'class' | 'interface' | 'type' | 'enum' | 'component' | 'export'; file: string; line: number; exported: boolean; }
export interface DependencyEdge { from: string; to: string; kind: 'import' | 'require' | 'dynamic-import'; }
export interface ApiEndpoint { method: string; route: string; file: string; line: number; framework?: string; confidence?: number; }
export interface CallRelationship { caller: string; callee: string; file: string; line: number; confidence: number; }
export interface ComplexitySignal { file: string; symbol: string; line: number; cyclomatic: number; cognitive: number; }
export interface DuplicateCodeSignal { files: string[]; lines: number; fingerprint: string; }
export interface ModuleBoundarySignal { from: string; to: string; fromArea: string; toArea: string; }
export interface CodeQualitySignals { largeFiles: Array<{ file: string; lines: number }>; largeFunctions: Array<{ file: string; name: string; line: number; lines?: number }>; largeClasses?: Array<{ file: string; name: string; line: number; lines: number }>; todoCount: number; fixmeCount: number; circularDependencies: string[][]; unreferencedModules?: string[]; complexity?: ComplexitySignal[]; duplicateCode?: DuplicateCodeSignal[]; moduleBoundarySignals?: ModuleBoundarySignal[]; technicalDebtScore?: number; }
export interface CodeIntelligence { filesAnalyzed: number; symbols: CodeSymbol[]; dependencyEdges: DependencyEdge[]; callRelationships?: CallRelationship[]; apiEndpoints: ApiEndpoint[]; entryPoints: string[]; architectureAreas: Record<string, string[]>; quality: CodeQualitySignals; frameworksCovered?: string[]; parserCoverage?: Record<string, number>; }
export interface IntelligenceInsight { id: string; domain: 'security' | 'browser' | 'dependencies' | 'architecture' | 'quality' | 'testing'; title: string; severity: 'critical' | 'warning' | 'info'; confidence: number; evidence: string[]; recommendation: string; }
export type ExtendedIntelligenceModuleId = 'project' | 'runtime' | 'platform' | 'build' | 'testing' | 'performance' | 'accessibility' | 'api' | 'database' | 'environment' | 'license' | 'documentation' | 'maintainability' | 'repository';
export interface IntelligenceModuleFinding { id: string; title: string; severity: 'critical' | 'warning' | 'info'; confidence: number; file?: string; line?: number; evidence: string; recommendation: string; }
export interface IntelligenceModuleResult { id: ExtendedIntelligenceModuleId; label: string; score: number; status: 'healthy' | 'review' | 'risk' | 'unknown'; summary: string; evidence: string[]; findings: IntelligenceModuleFinding[]; metrics: Record<string, number | string | boolean>; }
export interface ExtendedIntelligence { version: string; modules: Record<ExtendedIntelligenceModuleId, IntelligenceModuleResult>; overallScore: number; filesAnalyzed: number; generatedFindings: number; }
export type SecurityRuleCategory = 'secrets' | 'code-execution' | 'injection' | 'transport' | 'access-control' | 'information-exposure' | 'cryptography' | 'deserialization' | 'authentication' | 'authorization' | 'path-traversal' | 'request-forgery' | 'configuration';
export interface SecurityFinding { id: string; ruleId?: string; title: string; category?: SecurityRuleCategory; confidence?: 'high' | 'medium' | 'low'; severity: Severity; file: string; line: number; evidence: string; recommendation: string; scope?: 'production' | 'configuration'; falsePositivePossible?: boolean; certainty?: 'confirmed' | 'likely' | 'possible' | 'review-required'; }
export interface SecurityIntelligence { findings: SecurityFinding[]; score: number; filesScanned: number; rulesExecuted: number; knowledgeVersion?: string; categoryCounts?: Partial<Record<SecurityRuleCategory, number>>; }
export type BrowserName = 'Chrome' | 'Firefox' | 'Safari' | 'Edge' | 'Chrome Android' | 'Safari iOS';
export interface BrowserTarget { browser: BrowserName; version: number; }
export interface BrowserCompatibilityFinding { id?: string; feature: string; kind: 'javascript' | 'css' | 'web-api' | 'html'; file: string; line: number; status: 'supported' | 'partial' | 'unsupported' | 'unknown'; affectedBrowsers: BrowserName[]; recommendation: string; staticCheckOnly?: boolean; }
export interface BrowserCompatibilityIntelligence { targets: BrowserTarget[]; targetSource?: string; defaultTargetsUsed?: boolean; knowledgeVersion?: string; findings: BrowserCompatibilityFinding[]; score: number; filesScanned: number; featuresChecked: number; }
export interface TechnologyStack {
  language: Language; languages?: LanguageProfile[]; mixedLanguage?: boolean; primaryLanguage?: Language; secondaryLanguages?: LanguageProfile[];
  frameworks?: Framework[]; runtimes?: Runtime[]; technologyEvidence?: TechnologyEvidence[]; technologyDetections?: TechnologyDetection[]; technologyRelationships?: TechnologyRelationship[]; capabilities?: ProjectCapability[]; intelligenceInsights?: IntelligenceInsight[]; extendedIntelligence?: ExtendedIntelligence; v3RulePlatform?: V3ExecutionResult; knowledgeVersion?: string; dependencyIntelligence?: DependencyIntelligence; architecture?: ArchitectureIntelligence; codeIntelligence?: CodeIntelligence; securityIntelligence?: SecurityIntelligence; browserCompatibility?: BrowserCompatibilityIntelligence;
  framework: Framework; runtime: Runtime; packageManager: PackageManager; buildTool: BuildTool; frontend: Framework | 'None' | 'Unknown'; backend: Framework | 'None' | 'Unknown'; database: Database; configFiles: string[]; monorepo?: MonorepoTool | 'None'; cloudProvider?: CloudProvider | 'None'; confidence?: DetectionConfidence;
}
export type MonorepoTool = 'Cargo Workspaces' | 'Nx' | 'Turborepo' | 'Lerna' | 'Rush' | 'pnpm Workspaces' | 'Yarn Workspaces' | 'None';
export type CloudProvider = 'Vercel' | 'Netlify' | 'Railway' | 'Fly.io' | 'Render' | 'Cloudflare' | 'None';
export interface ScanStats { projectSize: number; filesFound: number; filesAnalyzed: number; filesIgnored: number; ignoredCategories: string[]; zipSize?: number; scanTimeMs?: number; memoryUsedMB?: number; rulesExecuted?: number; sampled?: boolean; truncated?: boolean; truncationReason?: string; contentBytesRead?: number; contentByteLimit?: number; }
export interface AnalysisCoverage { status: 'full' | 'partial'; filesAnalyzed: number; filesFound: number; fileCoveragePercent: number; reason?: string; }
export interface ProjectSummary { name: string; framework: Framework; language: Language; runtime: Runtime; packageManager: PackageManager; detectedConfigFiles: string[]; filesScanned: number; foldersScanned: number; scanStats: ScanStats; analysisCoverage?: AnalysisCoverage; }
export interface Issue { id: string; title: string; category: CategoryId; severity: Severity; description: string; reason: string; recommendation: string; affectedFile: string; detected?: string; expected?: string; impact?: string; suggestedAction?: string; }
export interface CategoryResult { id: CategoryId; label: string; status: CategoryStatus; score: number; issues: Issue[]; summary: string; }
export interface CompatibilityScore { runtime: number; dependencies: number; configuration: number; structure: number; environment: number; security: number; deployment: number; performance: number; overall: number; applicableCategories?: CategoryId[]; }
export interface AnalysisTrustMetadata { localOnly: boolean; networkAccessUsed: boolean; sourceUploaded: boolean; scoringFormula: string; scoreWeights: Record<string, number>; knowledgePacks: Array<{ id: string; version: string; schemaVersion: number; signed: boolean }>; limitations: string[]; execution?: { worker: boolean; cached: boolean; sampled: boolean; truncated: boolean; incremental?: boolean; changedFiles?: number; reusedFiles?: number }; }
export type AnalysisStage = 'idle' | 'uploading' | 'reading' | 'detecting' | 'analyzing' | 'scoring' | 'reporting' | 'completed' | 'error';
export interface TimelineStep { step: number; label: string; description: string; status: 'done' | 'active' | 'pending'; }
export interface AnalysisResult { id: string; createdAt: string; analysisVersion: string; classification: ProjectClassification; summary: ProjectSummary; stack: TechnologyStack; detectedFiles: DetectedFile[]; categories: CategoryResult[]; issues: Issue[]; score: CompatibilityScore; timeline: TimelineStep[]; notes: string[]; source: 'upload' | 'demo' | 'github'; trust?: AnalysisTrustMetadata; }
export interface AnalysisInput { fileName: string; files: ProjectFile[]; source: 'upload' | 'demo' | 'github'; scanStats: ScanStats; }
